Python/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("add", views.add, name="add"),
    path("edit", views.edit, name="edit"),
    path("saveedit", views.saveedit, name="saveedit"),
    path("<str:title>", views.gotoentry, name="gotoentry"),
    path("randompage", views.randompage, name="randompage")
]

Python/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

Python/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Python/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseBadRequest
from django.contrib import messages
from django import forms
from django.urls import reverse
import random
import sys
import os
import markdown2

from . import util

class NewTaskForm(forms.Form):
    title = forms.CharField(label="Page Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20}))
   
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def search(request):
    query = request.GET.get('q')
    entries = util.list_entries()
    sublist = []
    for entry in entries :
        if query.lower() == entry.lower() : 
            response = redirect(f'/wiki/{query}')
            return response 

    for entry in entries:
        if query.lower() in entry.lower() :
            sublist.append(entry)

    return render(request, "encyclopedia/search.html", {
         "query": query,
         "matches": sublist
    })

def create(request):

    return render(request, "encyclopedia/create.html", {
        "form": NewTaskForm()
    })

def add(request): 
    if request.method == "POST":
       form = NewTaskForm(request.POST)

    if form.is_valid():
        entries = util.list_entries()
        title = form.cleaned_data["title"]
        content = form.cleaned_data["content"]

        for entry in entries : 
            if title.lower() == entry.lower() :
                return render(request, "encyclopedia/create.html", {
                "form": form,
                "error": "Error! Title already in use."
                })
        # no errors, valid form
        # create new page and save to disk
        util.save_entry(title, content)
        #return HttpResponseRedirect(f"/{title}")
        return gotoentry(request, title)
    else:
        return render(request, "encyclopedia/create.html", {
            "form": form
        })

    return render(request, "encyclopedia/git.html")

def edit(request):
    if request.method == "POST":
       form = NewTaskForm(request.POST)
    if form.is_valid():
        return render(request, "encyclopedia/edit.html", {
            "form": form 
        })
def saveedit(request):
    if request.method == "POST":
       form = NewTaskForm(request.POST)

    if form.is_valid():
        title = form.cleaned_data["title"]
        content = form.cleaned_data["content"]
        # delete old entry in case of title change here 
        # no errors, valid form
        # create/overwrite page and save to disk
        util.save_entry(title, content)
        return gotoentry(request, title)
    else:
        return render(request, "encyclopedia/edit.html", {
            "form": form
        })
    #should never run here 
    return render(request, "encyclopedia/edit.html")

def gotoentry(request, title):
    entry = util.get_entry(f"{title}")
    htmlVersion = markdown2.markdown(entry, extras=['fenced-code-blocks'])

    return render(request, "encyclopedia/entry.html", {
        "entry": entry,
        "title": title.capitalize(), 
        "markdownX": htmlVersion
    })

def randompage(request):
    #entries = util.list_entries()
    #randomindex = random.randint(0, entries.count - 1)
    #title = entries[0]
    #title = "9999.md"
    #return render(request, "encyclopedia/edit.html")
    #return gotoentry(request, title)
    #return render(request, "encyclopedia/index.html", {
    #   "entries": util.list_entries()
    #})
    return render(request, "encyclopedia/create.html", {
        "form": NewTaskForm()
    })

    
    

Python/wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia 
{% endblock %}

{% block body %}
    
    <h1>add</h1>

{% endblock %}

Python/wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia 
{% endblock %}

{% block body %}
    
    <h1>Create Entry</h1>

    <form action="{% url 'encyclopedia:add' %}" method=POST id="entryform">
        {% csrf_token %}
        {{ error }}
        <p></p>
        Title: 
        {{ form.title }}
        <input type="submit">
        <p></p>
        {{ form.content }}
    </form>
    <br>
    <!--<textarea rows="4" cols="50" name="content" form="entryform" placeholder="Enter Markdown and HTML for your new page here"></textarea>
    -->
{% endblock %}

Python/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia 
{% endblock %}

{% block body %}
    
    <h1>Edit Entry</h1>

    <form action="{% url 'encyclopedia:saveedit' %}" method=POST id="entryform">
        {% csrf_token %}
        {{ error }}
        <p></p>
        Title: 
        {{ form.title }}
        <input type="submit" value="Save">
        <p></p>
        {{ form.content }}
    </form>

    <br>
    <!--<textarea rows="4" cols="50" name="content" form="entryform" placeholder="Enter Markdown and HTML for your new page here"></textarea>
    -->
{% endblock %}

Python/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia X
{% endblock %}

{% block body %}
    <style>
        input[type=submit].link { border: none; background: none; display: inline; color: blue; text-decoration: underline; }
    </style>
    {% if entry %}
        <h1> {{ title }} </h1> 
        
        <!-- <a href="{% url 'encyclopedia:edit' %}">edit</a> -->
        <form action="{% url 'encyclopedia:edit' %}" method=POST id="editEntryForm">
            {% csrf_token %}
            <input value = "Edit" type=submit class="link" />
            <input type=hidden value= "{{ entry }}" name = "content">
            <input type=hidden value= "{{ title }}" name = "title">
        </form>
        
        <p>
            <!-- {{ entry }} -->
           {{ markdownX | safe }}
        </p>
        
    {% else %}
        <h1>Error: This page does not Exist.</h1>
        <h2>Try creating it!</h2>
    {% endif %}

{% endblock %}

Python/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

Python/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method=GET>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Python/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia X
{% endblock %}

{% block body %}
    
        <h1>SEARCH</h1>
        {{ query }}

        {% for match in matches %}
            <li><a href="{{ match }}">{{ match }}</a></li>
        {% endfor %}
    
{% endblock %}